name: Lighthouse

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6am UTC
  workflow_call:
  workflow_dispatch:

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.15.x
          lhci autorun